### ISSUE TITLE
Modify batch request to prevent 400 when empty result set

### ISSUE THREAD

**Issue by afagard** [dacastro4/laravel-gmail#203]
If you have a request with `preload()` and the result set is 0 (no results), then the `batchRequest()` function will return a 400.

You can simply check if `$allMessages` is == 0, if so, just return an empty array in this function.

```
public function batchRequest($allMessages) {
        $messages = [];

        if (count($allMessages) == 0) {
            return $messages;
        }

		$this->client->setUseBatch(true);

		$batch = $this->service->createBatch();

		foreach ($allMessages as $key => $message) {
			$batch->add($this->getRequest($message->getId()), $key);
		}

		$messagesBatch = $batch->execute();

		$this->client->setUseBatch(false);

		foreach ($messagesBatch as $message) {
			$messages[] = new Mail($message);
		}

		return $messages;
	}
```
```

**Comment by dacastro4** [comment]
Fixed in v.5.1.21

**Comment by uacode** [comment]
@dacastro4 Hello, can you push FIX to 5.0 version (PHP 7.4)
Thanks

**Comment by troygilbert** [comment]
I'm still getting this issue, and I don't see any fixes related to this issue.

**Comment by troygilbert** [comment]
Just realized I don't have this fix because we're still on PHP 7.4. Would love to see this fix in v5.1 (or relax the the PHP 8 requirement on v5.1.21 if it's not actually required).

**Comment by troygilbert** [comment]
Actually, it looks like the v5.1.21 tag was made right before composer was updated to be `PHP: ^7.4|^8.0`, so I guess all we really need is a new tag?
