### ISSUE TITLE
getHtmlBody() doesn't find body, when nested parts (f.e. multipart/related)

### ISSUE THREAD

**Issue by martinschenk** [dacastro4/laravel-gmail#88]
getHtmlBody() sometimes can't find the body and the attachments because they are deeper nested.
This happens for example if you receive an email which was created with Spark from spark mail app with inline photos.

For example the body can  be in payload->parts[1]->parts[0]->body->data.
![Bildschirmfoto 2019-06-10 um 20 36 55](https://user-images.githubusercontent.com/635827/59217999-82bdc500-8bbf-11e9-9774-6a9509f55df9.png)

Here an example of my workaround code. It describes the problem well i think.

                       function iterateParts($collectionToCheck){
                            global $partsCollection;
                            $plucked = $collectionToCheck->pluck('parts');
                            if ($plucked){
                                foreach ($plucked as $pluck){
                                    if (!empty($pluck)){
                                        $partsCollection[]=($pluck);
                                        $pluck = collect($pluck);
                                        iterateParts($pluck);
                                    }
                                }
                            }
                            $partsCollection = collect($partsCollection);
                            return $partsCollection->flatten();
                        }

                        function getHtmlBodyFromParts($parts){
                            foreach ($parts as $part){
                                //dump($part->mimeType);
                                if ($part->mimeType == 'text/html'){
                                    return base64Decode($part->body->data);
                                }
                            }
                        }

                        function base64Decode($data){
                            $data = str_replace('_', '/', str_replace('-', '+', $data));
                            return base64_decode($data);
                        }

                        $partsCollection = iterateParts($messageCollection);
                        $htmlBody = getHtmlBodyFromParts($partsCollection);

Same happens to the Attachments:
They can be in payload->parts[1]->parts[1]->body->attachmentId

![Bildschirmfoto 2019-06-10 um 20 40 25](https://user-images.githubusercontent.com/635827/59218220-0081d080-8bc0-11e9-9c34-648898b2bd0c.png)

I couldn't create a workaround for that up to now because i don't know how to do it (i tried). It would be great if you could add this.
Maybe it has to do with your traverseData() and extractFromBody() functions.

Thanks and regards

**Comment by dacastro4** [comment]
@martinschenk that's another level of complexity and a really deep body lol. I think we could try something like your workaround and check if the `collection_key` is a `parts` value and keep iterating until is not and get the body (?) maybe...

**Comment by martinschenk** [comment]
@dacastro4 i will try to integrate it.
1) Iteration trough all parts of a message and  return a collection of all parts in the message.
2.) get text/html and /plain by looging for $part->mimeType 
3.) getting all attachments by searching in parts collection for if(!empty($part->body->attachmentId))

**Comment by martinschenk** [comment]
@dacastro4 i added this to a new pull request #91 

Created new trait 'HasParts' with recursive function to get all parts of a message flattened.
I have adapted the methods in Mail.php to find text and attachments independent of how deep the parts are nested.
Please check if the old methods extractFromBody and traverseData are still necesary. I think they are not used (anymore).
I have made several tests and for me it works well up to now. 
Regards.

**Comment by martinschenk** [comment]
@dacastro4 here a small correction in getBody()

     if (!$parts->isEmpty()) {

other wise doesn't find $this->payload->body->data
Here the complete method:

        public function getBody($type = 'text/plain')
    {
        $parts = $this->getAllParts(collect([$this->payload]));
        if (!$parts->isEmpty()) {
            foreach ($parts as $part) {
                if ($part->mimeType == $type) {
                    return $part->body->data;
                    //if there are no parts in payload, try to get data from body->data
                } elseif ($this->payload->body->data) {
                    return $this->payload->body->data;
                }
            }
        } else {
            return $this->payload->body->data;
        }
        return null;
    }

**Comment by dacastro4** [comment]
fixed in #87

**Comment by samaphp** [comment]
Thank you guys for fixing the main issue, since there was a kind of email where I receive the body NULL but now it's fixed. There is only one issue is still remain while I'm testing all kind of NULL email messages that I faced before. So, I believe this issue still exists in v2.0 in one case.
The HTML body is null when receiving an email from Mailchimp's service https://tinyletter.com This service is a free service to send newsletters.

Not sure what is the issue exactly but I'm getting the HTML body as NULL.
I just sent a one-line message with no inline photos ..

<img width="1074" alt="Screenshot 2019-07-19 at 15 26 56" src="https://user-images.githubusercontent.com/531627/61534983-bea73e00-aa39-11e9-9079-144719d08304.png">


Thanks!
